include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Style
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    
    # Errors
    avoid_print: false
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    
    # Best practices
    always_declare_return_types: true
    annotate_overrides: true
    prefer_single_quotes: true
    require_trailing_commas: true
    
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  
  errors:
    invalid_annotation_target: ignore